//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENT3DRECONSTRUCTIONCORE_HH
#define _COMPONENT3DRECONSTRUCTIONCORE_HH
	
#include "aceSmartSoft.hh"
#include "DomainVision/Comm3dPointCloud.hh"
#include "ParameterStateStruct.hh"
#include <iostream>
#include <opencv2/rgbd/kinfu.hpp>

class Component3dReconstructionCore
{
private:

public:
	Component3dReconstructionCore();
	void setInitialParameters(const ParameterStateStruct& p);
	static void fromCvMat(const cv::Mat& in, DomainVision::Comm3dPointCloud& out);

	cv::Ptr<cv::kinfu::KinFu> kinfu;
	cv::Ptr<cv::kinfu::Params> params;
};
	
#endif
