//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "Component3dReconstructionAcePortFactory.hh"

// create a static instance of the default AcePortFactory
static Component3dReconstructionAcePortFactory acePortFactory;

Component3dReconstructionAcePortFactory::Component3dReconstructionAcePortFactory()
{  
	componentImpl = 0;
	Component3dReconstruction::instance()->addPortFactory("ACE_SmartSoft", this);
}

Component3dReconstructionAcePortFactory::~Component3dReconstructionAcePortFactory()
{  }

void Component3dReconstructionAcePortFactory::initialize(Component3dReconstruction *component, int argc, char* argv[])
{
	if(component->connections.component.defaultScheduler != "DEFAULT") {
		ACE_Sched_Params sched_params(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(component->connections.component.defaultScheduler == "FIFO") {
			sched_params.policy(ACE_SCHED_FIFO);
			sched_params.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(component->connections.component.defaultScheduler == "RR") {
			sched_params.policy(ACE_SCHED_RR);
			sched_params.priority(ACE_THR_PRI_RR_MIN);
		}
		// create new instance of the SmartSoft component with customized scheuling parameters 
		componentImpl = new Component3dReconstructionImpl(component->connections.component.name, argc, argv, sched_params);
	} else {
		// create new instance of the SmartSoft component
		componentImpl = new Component3dReconstructionImpl(component->connections.component.name, argc, argv);
	}
}

int Component3dReconstructionAcePortFactory::onStartup()
{
	return componentImpl->startComponentInfrastructure();
}

Smart::IPushClientPattern<DomainVision::CommDepthImage> * Component3dReconstructionAcePortFactory::createDepthImagePushServiceIn()
{
	return new SmartACE::PushClient<DomainVision::CommDepthImage>(componentImpl);
}


Smart::IPushServerPattern<DomainVision::Comm3dPointCloud> * Component3dReconstructionAcePortFactory::createPointCloudPushServiceOut(const std::string &serviceName)
{
	return new SmartACE::PushServer<DomainVision::Comm3dPointCloud>(componentImpl, serviceName);
}

Smart::IQueryServerPattern<CommManipulatorObjects::CommManipulatorId, DomainVision::Comm3dPointCloud> * Component3dReconstructionAcePortFactory::createPointCloudQueryServiceAnsw(const std::string &serviceName)
{
	return new SmartACE::QueryServer<CommManipulatorObjects::CommManipulatorId, DomainVision::Comm3dPointCloud>(componentImpl, serviceName);
}

Smart::IPushServerPattern<DomainVision::CommVideoImage> * Component3dReconstructionAcePortFactory::createRGBImagePushServiceOut(const std::string &serviceName)
{
	return new SmartACE::PushServer<DomainVision::CommVideoImage>(componentImpl, serviceName);
}


SmartACE::SmartComponent* Component3dReconstructionAcePortFactory::getComponentImpl()
{
	return componentImpl;
}

int Component3dReconstructionAcePortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	componentImpl->stopComponentInfrastructure(timeoutTime);
	return 0;
}

void Component3dReconstructionAcePortFactory::destroy()
{
	// clean-up component's internally used resources (internally used communication middleware) 
	componentImpl->cleanUpComponentResources();
	delete componentImpl;
}
