//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef COMPONENT3DRECONSTRUCTION_PORTFACTORYINTERFACE_HH_
#define COMPONENT3DRECONSTRUCTION_PORTFACTORYINTERFACE_HH_

// include communication objects
#include <DomainVision/Comm3dPointCloud.hh>
#include <DomainVision/Comm3dPointCloudACE.hh>
#include <DomainVision/CommDepthImage.hh>
#include <DomainVision/CommDepthImageACE.hh>
#include <CommManipulatorObjects/CommManipulatorId.hh>
#include <CommManipulatorObjects/CommManipulatorIdACE.hh>
#include <DomainVision/CommVideoImage.hh>
#include <DomainVision/CommVideoImageACE.hh>

#include <chrono>

// include component's main class
#include "Component3dReconstruction.hh"

// forward declaration
class Component3dReconstruction;

class Component3dReconstructionPortFactoryInterface {
public:
	Component3dReconstructionPortFactoryInterface() { };
	virtual ~Component3dReconstructionPortFactoryInterface() { };

	virtual void initialize(Component3dReconstruction *component, int argc, char* argv[]) = 0;
	virtual int onStartup() = 0;

	virtual Smart::IPushClientPattern<DomainVision::CommDepthImage> * createDepthImagePushServiceIn() = 0;
	
	virtual Smart::IPushServerPattern<DomainVision::Comm3dPointCloud> * createPointCloudPushServiceOut(const std::string &serviceName) = 0;
	virtual Smart::IQueryServerPattern<CommManipulatorObjects::CommManipulatorId, DomainVision::Comm3dPointCloud> * createPointCloudQueryServiceAnsw(const std::string &serviceName) = 0;
	virtual Smart::IPushServerPattern<DomainVision::CommVideoImage> * createRGBImagePushServiceOut(const std::string &serviceName) = 0;

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) = 0;
	virtual void destroy() = 0;
};

#endif /* COMPONENT3DRECONSTRUCTION_PORTFACTORYINTERFACE_HH_ */
