//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "Component3dReconstruction.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "Component3dReconstructionAcePortFactory.hh"


// initialize static singleton pointer to zero
Component3dReconstruction* Component3dReconstruction::_component3dReconstruction = 0;

// constructor
Component3dReconstruction::Component3dReconstruction()
{
	std::cout << "constructor of Component3dReconstruction\n";
	
	// set all pointer members to NULL
	activity3dReconstruction = NULL;
	activity3dReconstructionTrigger = NULL;
	//component3dReconstruction = NULL;
	//coordinationPort = NULL;
	depthImagePushServiceIn = NULL;
	depthImagePushServiceInInputTaskTrigger = NULL;
	depthImagePushServiceInUpcallManager = NULL;
	pointCloudPushServiceOut = NULL;
	pointCloudQueryServiceAnsw = NULL;
	pointCloudQueryServiceAnswInputTaskTrigger = NULL;
	pointCloudQueryServiceAnswHandler = NULL;
	rGBImagePushServiceOut = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	param = NULL;
	
	// set default ini parameter values
	connections.component.name = "Component3dReconstruction";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.pointCloudPushServiceOut.serviceName = "PointCloudPushServiceOut";
	connections.pointCloudPushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.pointCloudQueryServiceAnsw.serviceName = "PointCloudQueryServiceAnsw";
	connections.pointCloudQueryServiceAnsw.roboticMiddleware = "ACE_SmartSoft";
	connections.rGBImagePushServiceOut.serviceName = "RGBImagePushServiceOut";
	connections.rGBImagePushServiceOut.roboticMiddleware = "ACE_SmartSoft";
	connections.depthImagePushServiceIn.wiringName = "DepthImagePushServiceIn";
	connections.depthImagePushServiceIn.serverName = "unknown";
	connections.depthImagePushServiceIn.serviceName = "unknown";
	connections.depthImagePushServiceIn.interval = 1;
	connections.depthImagePushServiceIn.roboticMiddleware = "ACE_SmartSoft";
	connections.activity3dReconstruction.minActFreq = 0.0;
	connections.activity3dReconstruction.maxActFreq = 0.0;
	connections.activity3dReconstruction.trigger = "PeriodicTimer";
	connections.activity3dReconstruction.periodicActFreq = 1.0;
	// scheduling default parameters
	connections.activity3dReconstruction.scheduler = "DEFAULT";
	connections.activity3dReconstruction.priority = -1;
	connections.activity3dReconstruction.cpuAffinity = -1;
	
	// initialize members of Component3dReconstructionROSExtension
	
	// initialize members of OpcUaBackendComponentGeneratorExtension
	
	// initialize members of PlainOpcUaComponent3dReconstructionExtension
	
}

void Component3dReconstruction::addPortFactory(const std::string &name, Component3dReconstructionPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void Component3dReconstruction::addExtension(Component3dReconstructionExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* Component3dReconstruction::getComponentImpl()
{
	return dynamic_cast<Component3dReconstructionAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void Component3dReconstruction::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode Component3dReconstruction::connectDepthImagePushServiceIn(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = depthImagePushServiceIn->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->depthImagePushServiceIn->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	depthImagePushServiceIn->subscribe(connections.depthImagePushServiceIn.interval);
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode Component3dReconstruction::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectDepthImagePushServiceIn(connections.depthImagePushServiceIn.serverName, connections.depthImagePushServiceIn.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void Component3dReconstruction::startAllTasks() {
	// start task Activity3dReconstruction
	if(connections.activity3dReconstruction.scheduler != "DEFAULT") {
		ACE_Sched_Params activity3dReconstruction_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.activity3dReconstruction.scheduler == "FIFO") {
			activity3dReconstruction_SchedParams.policy(ACE_SCHED_FIFO);
			activity3dReconstruction_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.activity3dReconstruction.scheduler == "RR") {
			activity3dReconstruction_SchedParams.policy(ACE_SCHED_RR);
			activity3dReconstruction_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		activity3dReconstruction->start(activity3dReconstruction_SchedParams, connections.activity3dReconstruction.cpuAffinity);
	} else {
		activity3dReconstruction->start();
	}
}

/**
 * Start all timers contained in this component
 */
void Component3dReconstruction::startAllTimers() {
}


Smart::TaskTriggerSubject* Component3dReconstruction::getInputTaskTriggerFromString(const std::string &client)
{
	if(client == "DepthImagePushServiceIn") return depthImagePushServiceInInputTaskTrigger;
	
	return NULL;
}


void Component3dReconstruction::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		// print out the actual parameters which are used to initialize the component
		std::cout << " \nComponentDefinition Initial-Parameters:\n" << COMP->getParameters() << std::endl;
		
		// initializations of Component3dReconstructionROSExtension
		
		// initializations of OpcUaBackendComponentGeneratorExtension
		
		// initializations of PlainOpcUaComponent3dReconstructionExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		Component3dReconstructionPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<Component3dReconstructionAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition Component3dReconstruction is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		pointCloudPushServiceOut = portFactoryRegistry[connections.pointCloudPushServiceOut.roboticMiddleware]->createPointCloudPushServiceOut(connections.pointCloudPushServiceOut.serviceName);
		pointCloudQueryServiceAnsw = portFactoryRegistry[connections.pointCloudQueryServiceAnsw.roboticMiddleware]->createPointCloudQueryServiceAnsw(connections.pointCloudQueryServiceAnsw.serviceName);
		pointCloudQueryServiceAnswInputTaskTrigger = new Smart::QueryServerTaskTrigger<CommManipulatorObjects::CommManipulatorId, DomainVision::Comm3dPointCloud>(pointCloudQueryServiceAnsw);
		rGBImagePushServiceOut = portFactoryRegistry[connections.rGBImagePushServiceOut.roboticMiddleware]->createRGBImagePushServiceOut(connections.rGBImagePushServiceOut.serviceName);
		
		// create client ports
		depthImagePushServiceIn = portFactoryRegistry[connections.depthImagePushServiceIn.roboticMiddleware]->createDepthImagePushServiceIn();
		
		// create InputTaskTriggers and UpcallManagers
		depthImagePushServiceInInputTaskTrigger = new Smart::InputTaskTrigger<DomainVision::CommDepthImage>(depthImagePushServiceIn);
		depthImagePushServiceInUpcallManager = new DepthImagePushServiceInUpcallManager(depthImagePushServiceIn);
		
		// create input-handler
		
		// create request-handlers
		pointCloudQueryServiceAnswHandler = new PointCloudQueryServiceAnswHandler(pointCloudQueryServiceAnsw);
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		if (stateSlave->defineStates("PushImage" ,"pushimage") != Smart::SMART_OK) std::cerr << "ERROR: defining state combinaion PushImage.pushimage" << std::endl;
		if (stateSlave->defineStates("QueryImage" ,"queryimage") != Smart::SMART_OK) std::cerr << "ERROR: defining state combinaion QueryImage.queryimage" << std::endl;
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.depthImagePushServiceIn.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::PushClient<DomainVision::CommDepthImage>*>(depthImagePushServiceIn)->add(wiringSlave, connections.depthImagePushServiceIn.wiringName);
		}
		
		// create parameter slave
		param = new SmartACE::ParameterSlave(component, &paramHandler);
		
		
		// create Task Activity3dReconstruction
		activity3dReconstruction = new Activity3dReconstruction(component);
		// configure input-links
		depthImagePushServiceInUpcallManager->attach(activity3dReconstruction);
		// configure task-trigger (if task is configurable)
		if(connections.activity3dReconstruction.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.activity3dReconstruction.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(activity3dReconstruction);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				activity3dReconstructionTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task Activity3dReconstruction" << std::endl;
			}
		} else if(connections.activity3dReconstruction.trigger == "DataTriggered") {
			activity3dReconstructionTrigger = getInputTaskTriggerFromString(connections.activity3dReconstruction.inPortRef);
			if(activity3dReconstructionTrigger != NULL) {
				activity3dReconstructionTrigger->attach(activity3dReconstruction, connections.activity3dReconstruction.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.activity3dReconstruction.inPortRef << " as activation source for Task Activity3dReconstruction" << std::endl;
			}
		} else
		{
			// setup default task-trigger as PeriodicTimer
			Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
			int microseconds = 1000*1000 / 1.0;
			if(microseconds > 0) {
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				triggerPtr->attach(activity3dReconstruction);
				// store trigger in class member
				activity3dReconstructionTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task Activity3dReconstruction" << std::endl;
			}
		}
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void Component3dReconstruction::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void Component3dReconstruction::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	depthImagePushServiceInUpcallManager->detach(activity3dReconstruction);
	// unlink the TaskTrigger
	if(activity3dReconstructionTrigger != NULL){
		activity3dReconstructionTrigger->detach(activity3dReconstruction);
		delete activity3dReconstruction;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers
	delete depthImagePushServiceInInputTaskTrigger;
	delete depthImagePushServiceInUpcallManager;

	// destroy client ports
	delete depthImagePushServiceIn;

	// destroy server ports
	delete pointCloudPushServiceOut;
	delete pointCloudQueryServiceAnsw;
	delete pointCloudQueryServiceAnswInputTaskTrigger;
	delete rGBImagePushServiceOut;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	delete pointCloudQueryServiceAnswHandler;
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	delete param;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of Component3dReconstructionROSExtension
	
	// destruction of OpcUaBackendComponentGeneratorExtension
	
	// destruction of PlainOpcUaComponent3dReconstructionExtension
	
}

void Component3dReconstruction::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("Component3dReconstruction.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load Component3dReconstruction.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: Component3dReconstruction.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client DepthImagePushServiceIn
		parameter.getString("DepthImagePushServiceIn", "serviceName", connections.depthImagePushServiceIn.serviceName);
		parameter.getString("DepthImagePushServiceIn", "serverName", connections.depthImagePushServiceIn.serverName);
		parameter.getString("DepthImagePushServiceIn", "wiringName", connections.depthImagePushServiceIn.wiringName);
		parameter.getInteger("DepthImagePushServiceIn", "interval", connections.depthImagePushServiceIn.interval);
		if(parameter.checkIfParameterExists("DepthImagePushServiceIn", "roboticMiddleware")) {
			parameter.getString("DepthImagePushServiceIn", "roboticMiddleware", connections.depthImagePushServiceIn.roboticMiddleware);
		}
		
		// load parameters for server PointCloudPushServiceOut
		parameter.getString("PointCloudPushServiceOut", "serviceName", connections.pointCloudPushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("PointCloudPushServiceOut", "roboticMiddleware")) {
			parameter.getString("PointCloudPushServiceOut", "roboticMiddleware", connections.pointCloudPushServiceOut.roboticMiddleware);
		}
		// load parameters for server PointCloudQueryServiceAnsw
		parameter.getString("PointCloudQueryServiceAnsw", "serviceName", connections.pointCloudQueryServiceAnsw.serviceName);
		if(parameter.checkIfParameterExists("PointCloudQueryServiceAnsw", "roboticMiddleware")) {
			parameter.getString("PointCloudQueryServiceAnsw", "roboticMiddleware", connections.pointCloudQueryServiceAnsw.roboticMiddleware);
		}
		// load parameters for server RGBImagePushServiceOut
		parameter.getString("RGBImagePushServiceOut", "serviceName", connections.rGBImagePushServiceOut.serviceName);
		if(parameter.checkIfParameterExists("RGBImagePushServiceOut", "roboticMiddleware")) {
			parameter.getString("RGBImagePushServiceOut", "roboticMiddleware", connections.rGBImagePushServiceOut.roboticMiddleware);
		}
		
		// load parameters for task Activity3dReconstruction
		parameter.getDouble("Activity3dReconstruction", "minActFreqHz", connections.activity3dReconstruction.minActFreq);
		parameter.getDouble("Activity3dReconstruction", "maxActFreqHz", connections.activity3dReconstruction.maxActFreq);
		parameter.getString("Activity3dReconstruction", "triggerType", connections.activity3dReconstruction.trigger);
		if(connections.activity3dReconstruction.trigger == "PeriodicTimer") {
			parameter.getDouble("Activity3dReconstruction", "periodicActFreqHz", connections.activity3dReconstruction.periodicActFreq);
		} else if(connections.activity3dReconstruction.trigger == "DataTriggered") {
			parameter.getString("Activity3dReconstruction", "inPortRef", connections.activity3dReconstruction.inPortRef);
			parameter.getInteger("Activity3dReconstruction", "prescale", connections.activity3dReconstruction.prescale);
		}
		if(parameter.checkIfParameterExists("Activity3dReconstruction", "scheduler")) {
			parameter.getString("Activity3dReconstruction", "scheduler", connections.activity3dReconstruction.scheduler);
		}
		if(parameter.checkIfParameterExists("Activity3dReconstruction", "priority")) {
			parameter.getInteger("Activity3dReconstruction", "priority", connections.activity3dReconstruction.priority);
		}
		if(parameter.checkIfParameterExists("Activity3dReconstruction", "cpuAffinity")) {
			parameter.getInteger("Activity3dReconstruction", "cpuAffinity", connections.activity3dReconstruction.cpuAffinity);
		}
		
		// load parameters for Component3dReconstructionROSExtension
		
		// load parameters for OpcUaBackendComponentGeneratorExtension
		
		// load parameters for PlainOpcUaComponent3dReconstructionExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
		paramHandler.loadParameter(parameter);
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
