//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DepthImagePushServiceInUpcallManager.hh"

DepthImagePushServiceInUpcallManager::DepthImagePushServiceInUpcallManager(
	Smart::InputSubject<DomainVision::CommDepthImage> *subject,
	const int &prescaleFactor)
	:	Smart::IInputHandler<DomainVision::CommDepthImage>(subject, prescaleFactor)
{  }
DepthImagePushServiceInUpcallManager::~DepthImagePushServiceInUpcallManager()
{  }

void DepthImagePushServiceInUpcallManager::notify_upcalls(const DomainVision::CommDepthImage &input)
{
	for(auto it=upcalls.begin(); it!=upcalls.end(); it++) {
		(*it)->on_DepthImagePushServiceIn(input);
	}
}

void DepthImagePushServiceInUpcallManager::attach(DepthImagePushServiceInUpcallInterface *upcall)
{
	upcalls.push_back(upcall);
}
void DepthImagePushServiceInUpcallManager::detach(DepthImagePushServiceInUpcallInterface *upcall)
{
	upcalls.remove(upcall);
}
