//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _DEPTHIMAGEPUSHSERVICEIN_UPCALL_MANAGER_HH
#define _DEPTHIMAGEPUSHSERVICEIN_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "DepthImagePushServiceInUpcallInterface.hh"

/** DepthImagePushServiceInUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort DepthImagePushServiceIn and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class DepthImagePushServiceInUpcallManager
:	public Smart::IInputHandler<DomainVision::CommDepthImage>
{
private:
	// list of associated updalls
	std::list<DepthImagePushServiceInUpcallInterface*> upcalls;

	// call the on_DepthImagePushServiceIn of all the attached DepthImagePushServiceInUpcallInterfaces
	void notify_upcalls(const DomainVision::CommDepthImage &input);
	
protected:
	virtual void handle_input(const DomainVision::CommDepthImage &input) {
		// relay input-handling to all attached DepthImagePushServiceInUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	DepthImagePushServiceInUpcallManager(
		Smart::InputSubject<DomainVision::CommDepthImage> *subject,
		const int &prescaleFactor=1
	);
	virtual ~DepthImagePushServiceInUpcallManager();
	
	void attach(DepthImagePushServiceInUpcallInterface *upcall);
	void detach(DepthImagePushServiceInUpcallInterface *upcall);
};

#endif
