//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _POINTCLOUDQUERYSERVICEANSWHANDLER_CORE_HH
#define _POINTCLOUDQUERYSERVICEANSWHANDLER_CORE_HH
		
#include "aceSmartSoft.hh"

#include <DomainVision/Comm3dPointCloud.hh>
#include <CommManipulatorObjects/CommManipulatorId.hh>

// include the input interfaces (if any)

// include all interaction-observer interfaces
#include <PointCloudQueryServiceAnswHandlerObserverInterface.hh>

class PointCloudQueryServiceAnswHandlerCore 
:	public Smart::IInputHandler<std::pair<Smart::QueryIdPtr,CommManipulatorObjects::CommManipulatorId>>
,	public Smart::TaskTriggerSubject
{
private:
virtual void handle_input(const std::pair<Smart::QueryIdPtr,CommManipulatorObjects::CommManipulatorId> &input) override {
	this->handleQuery(input.first, input.second);
}


	virtual void updateAllCommObjects();

/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<PointCloudQueryServiceAnswHandlerObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(PointCloudQueryServiceAnswHandlerObserverInterface *observer);
	void detach_interaction_observer(PointCloudQueryServiceAnswHandlerObserverInterface *observer);

protected:
	
public:
	using IQueryServer = Smart::IQueryServerPattern<CommManipulatorObjects::CommManipulatorId, DomainVision::Comm3dPointCloud>;
	using QueryId = Smart::QueryIdPtr;
	PointCloudQueryServiceAnswHandlerCore(IQueryServer *server);
	virtual ~PointCloudQueryServiceAnswHandlerCore() = default;
	
protected:
	IQueryServer *server;
	//this user-method has to be implemented in derived classes
	virtual void handleQuery(const QueryId &id, const CommManipulatorObjects::CommManipulatorId& request) = 0;
};
#endif
