#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create subfolder combined-ini-files (if not yet created)
echo "create subfolder src-gen/combined-ini-files"
mkdir -p src-gen/combined-ini-files

# clean-up old combined-ini-files before they are generated again
echo "clean-up src-gen/combined-ini-files subfolder"
rm src-gen/combined-ini-files/*.ini

# create ini-file Component3dReconstruction.ini
echo "create ini-file Component3dReconstruction.ini"
cp src-gen/system/Component3dReconstruction.ini src-gen/combined-ini-files/
if [ -f src-gen/params/Component3dReconstruction.ini ]; then
  cat src-gen/params/Component3dReconstruction.ini >> src-gen/combined-ini-files/Component3dReconstruction.ini
fi

# create ini-file ComponentRealSenseV2Server.ini
echo "create ini-file ComponentRealSenseV2Server.ini"
cp src-gen/system/ComponentRealSenseV2Server.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentRealSenseV2Server.ini ]; then
  cat src-gen/params/ComponentRealSenseV2Server.ini >> src-gen/combined-ini-files/ComponentRealSenseV2Server.ini
fi

# create ini-file ComponentVisualization.ini
echo "create ini-file ComponentVisualization.ini"
cp src-gen/system/ComponentVisualization.ini src-gen/combined-ini-files/
if [ -f src-gen/params/ComponentVisualization.ini ]; then
  cat src-gen/params/ComponentVisualization.ini >> src-gen/combined-ini-files/ComponentVisualization.ini
fi

